# Generated by Django 6.0.2 on 2026-02-22 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Укажите наименование столика",
                        max_length=50,
                        unique=True,
                        verbose_name="Наименование (номер) столика",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Укажите описание столика",
                        max_length=200,
                        verbose_name="Описание столика",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Укажите местоположение столика",
                        max_length=100,
                        verbose_name="Местоположение столика",
                    ),
                ),
                (
                    "seats",
                    models.PositiveIntegerField(
                        help_text="Укажите вместимость столика",
                        verbose_name="Вместимость столика",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Отметьте, подлежит ли столик бронированию",
                        verbose_name="Подлежит бронированию",
                    ),
                ),
            ],
            options={
                "verbose_name": "Столик",
                "verbose_name_plural": "Столики",
                "ordering": ["name"],
            },
        ),
    ]
