# Generated by Django 6.0.2 on 2026-02-22 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        help_text="Укажите, на какое время хотите забронированить столик",
                        verbose_name="Время начала бронирования",
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        help_text="Укажите, в какое время готовы освободить столик",
                        verbose_name="Время окончания бронирования",
                    ),
                ),
                (
                    "guests",
                    models.PositiveIntegerField(
                        help_text="Укажите количество гостей",
                        verbose_name="Количество гостей",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Создано"),
                            ("confirmed", "Подтверждено"),
                            ("canceled", "Отменено"),
                            ("completed", "Завершено"),
                        ],
                        default="created",
                        max_length=20,
                        verbose_name="Статус бронирования",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания бронирования"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата изменения бронирования"
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        help_text="Выберите столик",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reservations.table",
                        verbose_name="Столик",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Укажите посетителя",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Посетитель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Бронирование",
                "verbose_name_plural": "Бронирования",
                "ordering": ["start_time"],
            },
        ),
    ]
