# Generated by Django 6.0.2 on 2026-02-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0002_reservation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table",
            name="location",
            field=models.CharField(
                choices=[("hall", "В зале"), ("terrace", "На терассе")],
                default="hall",
                help_text="Выберите местоположение столика",
                max_length=20,
                verbose_name="Местоположение столика",
            ),
        ),
    ]
