# Generated by Django 4.2.2 on 2026-02-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0003_alter_table_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="token",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Token"
            ),
        ),
    ]
