# Generated by Django 4.2.2 on 2026-02-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0004_table_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="table",
            name="token",
        ),
        migrations.AddField(
            model_name="reservation",
            name="token",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Token"
            ),
        ),
    ]
