# Generated by Django 4.2.2 on 2026-02-24 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0005_remove_table_token_reservation_token"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="table",
            options={
                "ordering": ["id"],
                "verbose_name": "Столик",
                "verbose_name_plural": "Столики",
            },
        ),
        migrations.AlterField(
            model_name="reservation",
            name="table",
            field=models.ForeignKey(
                help_text="Выберите столик",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="reservations.table",
                verbose_name="Столик",
            ),
        ),
    ]
