# Generated by Django 4.2.2 on 2026-02-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "history",
                    models.TextField(blank=True, verbose_name="История ресторана"),
                ),
                (
                    "mission",
                    models.TextField(blank=True, verbose_name="Миссия ресторана"),
                ),
                (
                    "values",
                    models.TextField(blank=True, verbose_name="Ценности ресторана"),
                ),
            ],
            options={
                "verbose_name": "О ресторане",
                "verbose_name_plural": "О ресторане",
            },
        ),
        migrations.CreateModel(
            name="Contacts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "restaurant_name",
                    models.CharField(max_length=200, verbose_name="Название ресторана"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=35, verbose_name="Телефон"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, unique=True, verbose_name="Почта"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Адрес ресторана"
                    ),
                ),
                (
                    "work_hours",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Часы работы"
                    ),
                ),
            ],
            options={
                "verbose_name": "Контакты и общая информация",
                "verbose_name_plural": "Контакты и общая информация",
            },
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Имя")),
                ("email", models.EmailField(max_length=254, verbose_name="Почта")),
                ("message", models.TextField(verbose_name="Сообщение")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
            ],
            options={
                "verbose_name": "Обратная связь",
                "verbose_name_plural": "Обратная связь",
            },
        ),
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок")),
                ("subtitle", models.TextField(blank=True, verbose_name="Подзаголовок")),
                (
                    "hall_title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Заголовок зала"
                    ),
                ),
                (
                    "hall_description",
                    models.TextField(blank=True, verbose_name="Описание зала"),
                ),
                (
                    "hall_image",
                    models.ImageField(
                        blank=True, upload_to="static/images/", verbose_name="Фото зала"
                    ),
                ),
                (
                    "terrace_title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Заголовок террасы"
                    ),
                ),
                (
                    "terrace_description",
                    models.TextField(blank=True, verbose_name="Описание террасы"),
                ),
                (
                    "terrace_image",
                    models.ImageField(
                        blank=True,
                        upload_to="static/images/",
                        verbose_name="Фото террасы",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Главная страница",
                "verbose_name_plural": "Главная страница",
            },
        ),
        migrations.CreateModel(
            name="Services",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название услуги"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание услуги"),
                ),
            ],
            options={
                "verbose_name": "Услуга",
                "verbose_name_plural": "Услуги",
            },
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="Имя сотрудника"),
                ),
                ("role", models.CharField(max_length=150, verbose_name="Должность")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Характеристика"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, upload_to="static/team/", verbose_name="Фото"
                    ),
                ),
            ],
            options={
                "verbose_name": "Сотрудник",
                "verbose_name_plural": "Сотрудники",
            },
        ),
    ]
