# Generated by Django 4.2.2 on 2026-02-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="hall_image",
            field=models.ImageField(
                blank=True, upload_to="home/", verbose_name="Фото зала"
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="terrace_image",
            field=models.ImageField(
                blank=True, upload_to="home/", verbose_name="Фото террасы"
            ),
        ),
    ]
