# Generated by Django 4.2.2 on 2026-02-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_alter_homepage_hall_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="photo",
            field=models.ImageField(blank=True, upload_to="team/", verbose_name="Фото"),
        ),
    ]
