# Generated by Django 4.2.2 on 2026-02-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_alter_staff_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Values",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.TextField(blank=True, verbose_name="Ценность ресторана"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
            ],
            options={
                "verbose_name": "Ценность",
                "verbose_name_plural": "Ценности",
            },
        ),
        migrations.RemoveField(
            model_name="aboutpage",
            name="values",
        ),
        migrations.AddField(
            model_name="aboutpage",
            name="values",
            field=models.ManyToManyField(
                blank=True, to="content.values", verbose_name="Ценности ресторана"
            ),
        ),
    ]
